### ISSUE TITLE
(TypeError) : Cannot read property 'digest' of undefined(Error logging-in chrome)

### ISSUE THREAD

**Issue by alison-man** [Peergos/Peergos#642] opened 2020-03-06 11:42 UTC
(TypeError) : Cannot read property 'digest' of undefined(Error logging-in chrome)

**Comment by ianopolous** [comment] 2020-03-06 17:37
What server is this using or is this a local build?

**Comment by ianopolous** [comment] 2020-03-06 17:49
Closing as dupe of: https://github.com/Peergos/Peergos/issues/637

**Closed by ianopolous** 2020-03-06 17:49 UTC
