### ISSUE TITLE
I build web-ui at local and run it  how can i slove these problem

### ISSUE THREAD

**Issue by alison-man** [Peergos/Peergos#634] opened 2020-02-12 11:00 UTC
(1)Error signing up with Google Chrome-80 but with Firefox normal?
err-msg: (TypeError):Cannot read property 'digest' of undefined

(2)I want more storage what's the next step when i send a more storage request?

thanks

**Comment by ianopolous** [comment] 2020-02-13 17:17
After you request more storage, an admin on the instance you signed up to needs to approve it.

**Comment by ianopolous** [comment] 2020-03-06 17:38
Closing as dupe of https://github.com/Peergos/Peergos/issues/637

**Closed by ianopolous** 2020-03-06 17:38 UTC
